# Generated by Django 5.1.3 on 2025-12-01 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0014_alter_gradeentry_assignment_date_reportcardgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2025, 12, 1)),
        ),
    ]
