# Generated by Django 5.1.3 on 2025-12-16 09:51

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_alter_registration_date_of_birth_and_more'),
        ('gradebook', '0019_remove_reportcardgrade_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2025, 12, 16)),
        ),
        migrations.CreateModel(
            name='HistoricalStudentAttendance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('S', 'Sick'), ('P', 'Permit'), ('A', 'Absent'), ('L', 'Late')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.student')),
            ],
            options={
                'verbose_name': 'historical student attendance',
                'verbose_name_plural': 'historical student attendances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
