# Generated by Django 5.1.3 on 2025-12-22 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_alter_schoollevel_options_and_more'),
        ('gradebook', '0025_alter_gradeentry_assignment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudentattendance',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudentattendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='historicalstudentreportcard',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='historicalstudentreportcard',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudentreportcard',
            name='level',
        ),
        migrations.RemoveField(
            model_name='historicalstudentreportcard',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalstudentreportcard',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
        migrations.AlterModelOptions(
            name='rubricindicator',
            options={'verbose_name': 'Rubric indicator', 'verbose_name_plural': 'Rubric Indicators'},
        ),
        migrations.RemoveField(
            model_name='gradeentry',
            name='school_level',
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.gradelevel'),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passinggrade',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.gradelevel'),
        ),
        migrations.AlterField(
            model_name='studentreportcard',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_level_reportcard', to='admission.gradelevel'),
        ),
        migrations.AlterField(
            model_name='studentrubrics',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.gradelevel'),
        ),
        migrations.DeleteModel(
            name='HistoricalReportcardGrade',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentAttendance',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentReportcard',
        ),
    ]
