# Generated by Django 5.1.3 on 2026-03-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_alter_schoollevel_options_and_more'),
        ('gradebook', '0026_remove_historicalstudentattendance_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='level',
            field=models.ForeignKey(default='--', on_delete=django.db.models.deletion.CASCADE, to='admission.gradelevel'),
        ),
    ]
