# Generated by Django 5.1.3 on 2026-03-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_alter_schoollevel_options_and_more'),
        ('gradebook', '0027_alter_gradeentry_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='academic_year',
        ),
        migrations.AlterField(
            model_name='assignmenthead',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.gradelevel'),
        ),
        migrations.CreateModel(
            name='ReportcardBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('reportcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.studentreportcard')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.rubric')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRubrics',
        ),
    ]
