# Generated by Django 5.1.3 on 2026-03-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0028_remove_rubric_academic_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportcardBehaviour',
        ),
    ]
