# Generated by Django 5.1.3 on 2026-03-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_alter_schoollevel_options_and_more'),
        ('gradebook', '0029_delete_reportcardbehaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportcardBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mid', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_level_reportcard_behaviour', to='admission.gradelevel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.learningperiod')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.rubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
