# Generated by Django 5.1.3 on 2025-12-02 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0015_alter_gradeentry_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdetail',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2025, 12, 2)),
        ),
    ]
