# Generated by Django 5.1.3 on 2025-12-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_alter_registration_date_of_birth_and_more'),
        ('gradebook', '0017_alter_gradeentry_assignment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('S', 'Sick'), ('P', 'Permit'), ('A', 'Absent'), ('L', 'Late')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
