# Generated by Django 5.1.3 on 2025-12-19 04:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_remove_gradelevel_school_level_and_more'),
        ('gradebook', '0023_alter_rubric_options_remove_gradeentry_school_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalassignmenthead',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='historicalassignmenthead',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalassignmenthead',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={},
        ),
        migrations.RemoveField(
            model_name='gradeentry',
            name='level',
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='school_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.schoollevel'),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2025, 12, 19)),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.schoollevel'),
        ),
        migrations.DeleteModel(
            name='HistoricalAssignmentDetail',
        ),
        migrations.DeleteModel(
            name='HistoricalAssignmentHead',
        ),
    ]
